# Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

C:\Users\bhuma\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


# Importing the Dataset.

In [2]:
data_fake=pd.read_csv(r"D:\Project IRT\fake[1].csv")
data_true=pd.read_csv(r"D:\Project IRT\true[1].csv")

# printing the data of fake.

In [3]:
data_fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

# Printing the data of true

In [4]:
data_true.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

# Assigning the classes to the Dataset.

In [5]:
data_fake["class"]=0
data_true["class"]=1

# checking the number of rows and columns in the dataset

In [6]:
data_fake.shape,data_true.shape

((23481, 5), (21417, 5))

# Manual testing for both the dataset.

In [7]:
data_fake_manual_testing=data_fake.tail(10)
for i in range(23480,23470,-1):
    data_fake.drop([i],axis=0,inplace=True)
data_true_manual_testing=data_true.tail(10)
for i in range(21416,21406,-1):
    data_true.drop([i],axis=0,inplace=True)

# Assigning classes to the dataset.

In [8]:
data_fake_manual_testing['class']=0
data_true_manual_testing['class']=1

C:\Users\bhuma\AppData\Local\Temp\ipykernel_1724\1676563180.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fake_manual_testing['class']=0
C:\Users\bhuma\AppData\Local\Temp\ipykernel_1724\1676563180.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_true_manual_testing['class']=1


# Merging Both the dataset.

In [9]:
data_merge=pd.concat([data_fake,data_true],axis=0)
data_merge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

# Dropping the unwanted Columns.

In [10]:
data=data_merge.drop(['title','subject','date'],axis=1)

# create a function to clean Text.

In [11]:
def wordopt(text):
    text=text.lower()
    text=re.sub('\[.*?\]','',text)
    text=re.sub("\\W"," ",text)
    text=re.sub('https?://\S+|WWW\.\S+','',text)
    text=re.sub('<.*?>+','',text)
    text=re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub('\n','',text)
    text=re.sub('\w*\d\w*','',text)
    return text

# Applying Function to text Column and Assigning X and Y

In [12]:
data['text']=data['text'].apply(wordopt)

In [13]:
x=data['text']
y=data['class']

# Defining Training and Testing Data and Splitting Them into &5-25 Percent Ratio. 

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

# Converting Raw Data into Matrix for further Process.

In [15]:
 from sklearn.feature_extraction.text import TfidfVectorizer
vectorization=TfidfVectorizer()
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)

# Creating the First Model

In [16]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

# Checking the model Accurarcy and classification Report.

In [17]:
pred_lr=LR.predict(xv_test)
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5894
           1       0.99      0.99      0.99      5326

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220



In [18]:
y_pred= LR.predict(xv_test)


In [19]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score,matthews_corrcoef
# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc_roc = roc_auc_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print(f'AUC-ROC: {auc_roc}')
print(f'Confusion Matrix:\n {conf_matrix}')
print(f'MCC: {mcc}')


Accuracy: 0.9876114081996435
Precision: 0.9857651245551602
Recall: 0.988171235448742
F1 Score: 0.986966713548992
AUC-ROC: 0.987638383248633
Confusion Matrix:
 [[5818   76]
 [  63 5263]]
MCC: 0.9751647071550568


# Creating the Second Model

In [20]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

# Checking the model Accurarcy and classification Report.

In [21]:
pred_DT=DT.predict(xv_test)
print(classification_report(y_test,pred_DT))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5894
           1       1.00      1.00      1.00      5326

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220



In [22]:
accuracy = accuracy_score(y_test, pred_DT)
precision = precision_score(y_test, pred_DT)
recall = recall_score(y_test, pred_DT)
f1 = f1_score(y_test, pred_DT)
auc_roc = roc_auc_score(y_test, pred_DT)
conf_matrix = confusion_matrix(y_test, pred_DT)
mcc = matthews_corrcoef(y_test, pred_DT)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print(f'AUC-ROC: {auc_roc}')
print(f'Confusion Matrix:\n {conf_matrix}')
print(f'MCC: {mcc}')

Accuracy: 0.9955436720142602
Precision: 0.9954921111945906
Recall: 0.9951182876455126
F1 Score: 0.9953051643192488
AUC-ROC: 0.9955231750409442
Confusion Matrix:
 [[5870   24]
 [  26 5300]]
MCC: 0.9910643458072824


In [23]:
DT.score(xv_test,y_test)

0.9955436720142602

# Creating the third Model

In [24]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(max_features=1000,stop_words='english')
x_train_vectorized=vectorizer.fit_transform(x_train)
x_test_vectorized=vectorizer.transform(x_test)
NB_classifier=MultinomialNB()
NB_classifier.fit(x_train_vectorized,y_train)

MultinomialNB()

# Checking the model Accurarcy and classification Report.

In [25]:
vectorizer=TfidfVectorizer(max_features=1000,stop_words='english')
x_train_vectorized = vectorizer.fit_transform(x_train)
x_test_vectorized = vectorizer.transform(x_test)
y_pred_1= NB_classifier.predict(x_test_vectorized)
accuracy=accuracy_score(y_test,y_pred_1)
print(f"Accuracy:{accuracy:2f}")
print("\n Classification Report:")
print(classification_report(y_test,y_pred_1))

Accuracy:0.923084

 Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      5894
           1       0.92      0.92      0.92      5326

    accuracy                           0.92     11220
   macro avg       0.92      0.92      0.92     11220
weighted avg       0.92      0.92      0.92     11220



In [26]:
# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred_1)
precision = precision_score(y_test, y_pred_1)
recall = recall_score(y_test, y_pred_1)
f1 = f1_score(y_test, y_pred_1)
auc_roc = roc_auc_score(y_test, y_pred_1)
conf_matrix = confusion_matrix(y_test, y_pred_1)
mcc = matthews_corrcoef(y_test, y_pred_1)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print(f'AUC-ROC: {auc_roc}')
print(f'Confusion Matrix:\n {conf_matrix}')
print(f'MCC: {mcc}')


Accuracy: 0.9230837789661319
Precision: 0.9200075287031809
Recall: 0.917761922643635
F1 Score: 0.9188833536986559
AUC-ROC: 0.9228273474772297
Confusion Matrix:
 [[5469  425]
 [ 438 4888]]
MCC: 0.8457564485206723


# Checking for Fake News

In [27]:
def output_lable(n):
    if n==0:
        return "Fake News"
    elif n==1:
        return "Not A Fake News"
def manual_testing(news):
    testing_news={"text":[news]}
    new_def_test=pd.DataFrame(testing_news)
    new_def_test["text"]=new_def_test["text"].apply(wordopt)
    new_x_test=new_def_test["text"]
    new_xv_test=vectorization.transform(new_x_test)
    pred_LR=LR.predict(new_xv_test)
    pred_DT=DT.predict(new_xv_test)
    return print("\n\nLR PRediction :{}\nDT Prediction:{}".format(output_lable(pred_LR[0]),
                                                                  output_lable(pred_DT[0])))

In [28]:
news=str(input())
manual_testing(news)

Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t eve

In [29]:
news=str(input())
manual_testing(news)

WASHINGTON (Reuters) - Transgender people will be allowed for the first time to enlist in the U.S. military starting on Monday as ordered by federal courts, the Pentagon said on Friday, after President Donald Trump’s administration decided not to appeal rulings that blocked his transgender ban. Two federal appeals courts, one in Washington and one in Virginia, last week rejected the administration’s request to put on hold orders by lower court judges requiring the military to begin accepting transgender recruits on Jan. 1. A Justice Department official said the administration will not challenge those rulings. “The Department of Defense has announced that it will be releasing an independent study of these issues in the coming weeks. So rather than litigate this interim appeal before that occurs, the administration has decided to wait for DOD’s study and will continue to defend the president’s lawful authority in District Court in the meantime,” the official said, speaking on